<?php

namespace App\Libraries;

class SiteDefaults
{
    public static function settings(): array
    {
        return [
            'brand_name'                 => 'La Majestic',
            'brand_tagline'              => 'French Cuisine, Bar & Modern European Dining',
            'brand_logo'                 => 'assets/img/la-majestic-logo.png',
            'brand_address'              => '412 High St, Windsor VIC 3181, Australia',
            'brand_phone_primary'        => '+61 3 9939 9231',
            'brand_phone_secondary'      => '+61 406 747 883',
            'brand_email'                => 'infolamajestic@gmail.com',
            'brand_hours_weekday'        => '05.00 PM - 11.00 PM (Monday - Thursday)',
            'brand_hours_weekend'        => '01.00 PM - 11.00 PM (Friday - Sunday)',
            'brand_hours_note'           => 'Tuesday Closed',
            'whatsapp_number'            => '61406747883',
            'footer_note'                => 'Premium European Bar & Modern European Dining',

            'nav_home_label'             => 'Home',
            'nav_gallery_label'          => 'Gallery',
            'nav_menu_label'             => 'Our Menu',
            'nav_cart_label'             => 'Cart',
            'nav_book_label'             => 'Book Table',
            'nav_contact_label'          => 'Contact Us',
            'header_visit_title'         => 'Visit Us',
            'header_booking_title'       => 'Booking request',
            'header_find_table_label'    => 'find a table',
            'header_cart_label'          => 'cart',
            'mobile_book_label'          => 'Book Table',
            'footer_navigation_heading'  => 'Navigation',
            'footer_reservations_heading'=> 'Reservations',
            'footer_call_label'          => 'Call',
            'footer_email_label'         => 'Email',
            'footer_map_label'           => 'Google map',
            'footer_reserve_label'       => 'Reserve',
            'footer_cart_summary_label'  => 'Cart summary',
            'footer_copyright_suffix'    => 'All Rights Reserved.',

            'label_book_table'           => 'book a table',
            'label_add_to_cart'          => 'add to cart',
            'label_details'              => 'Details',
            'label_view_all_menu'        => 'view all menu',
            'label_view_details'         => 'view details',
            'label_browse_menu'          => 'browse menu',
            'label_send_whatsapp'        => 'send on whatsapp',
            'label_email_enquiry'        => 'email enquiry',
            'label_clear_cart'           => 'Clear cart',
            'label_continue_takeaway'    => 'Continue take away',
            'label_send_enquiry'         => 'send enquiry',
            'label_submit_takeaway'      => 'place takeaway order',
            'label_view_cart_and_order'  => 'view cart and checkout',
            'label_go_to_reservation'    => 'Go to table reservation',
            'label_take_away_this_dish'  => 'take away this dish',

            'home_offer_heading'         => 'We Offer Top Notch',
            'home_offer_text'            => 'From the delicious food to wonderful cocktails, La Majestic\'s offer is guaranteed to satisfy all of your taste buds.',
            'home_offer_subtitle'        => 'flavors for royalty',
            'home_story_title'           => 'Every Flavor Tells a Story',
            'home_story_text'            => 'At La Majestic, we invite you to embark on a culinary journey through Europe. Our restaurant is a celebration of authentic European flavors, artfully crafted dishes, and a dining experience that transports you to the heart of Europe.',
            'home_story_subtitle'        => 'Our story',
            'home_story_cta_label'       => 'Read More',
            'home_story_image_primary'   => 'assets/img/fine-dining.jpg',
            'home_story_image_secondary' => 'assets/img/european-cuisine.jpg',
            'home_special_dish_subtitle' => 'Special dish',
            'special_dish_slug'          => 'lobster-bisque',
            'home_menu_subtitle'         => 'Special selection',
            'home_menu_heading'          => 'Delicious Menu',
            'home_menu_cta_label'        => 'view all menu',
            'home_special_offer_subtitle'=> 'special offer',
            'home_special_offer_heading' => 'Best Specialties',
            'home_special_offer_cta_label' => 'view all menu',
            'home_gallery_subtitle'      => 'visual experience',
            'home_gallery_heading'       => 'Gallery',
            'home_strength_subtitle'     => 'why choose us',
            'home_strength_heading'      => 'Our Strength',
            'home_contact_title'         => 'Contact Us',
            'home_contact_form_button_label' => 'send enquiry',
            'reservation_heading'        => 'Online Reservation',
            'reservation_text'           => 'Booking request by phone or fill out the reservation form below.',
            'reservation_slots_json'     => json_encode(['2 Guests', '4 Guests', '6 Guests', 'Large Group']),
            'service_modes_json'         => json_encode(['Dinner Table', 'Private Celebration', 'Date Night', 'Group Dining']),
            'strengths_json'             => json_encode([
                ['title' => 'Authentic Flavours', 'text' => 'French cuisine and modern European dishes inspired by the best of the continent.', 'icon' => 'front_template/images/resource/why-icon-1.png'],
                ['title' => 'Elegant Ambience', 'text' => 'A warm dining room designed for memorable nights, celebrations, and date dinners.', 'icon' => 'front_template/images/resource/why-icon-2.png'],
                ['title' => 'Skilled Kitchen', 'text' => 'Artfully crafted dishes, refined sauces, and careful presentation in every course.', 'icon' => 'front_template/images/resource/why-icon-3.png'],
                ['title' => 'Book With Ease', 'text' => 'Reserve a table quickly by phone, email, or the booking section on this website.', 'icon' => 'front_template/images/resource/why-icon-4.png'],
            ]),

            'menu_page_intro'            => 'Discover signature French-European dishes, seafood, grills, desserts, and elegant takeaway favourites.',
            'menu_banner_image'          => 'front_template/images/background/banner-image-2.jpg',
            'menu_banner_subtitle'       => 'delicious and amazing',
            'menu_banner_title'          => 'Our Menu',
            'menu_cta_title'             => 'Ready To Order?',
            'menu_cta_text'              => 'Build your cart with your favourite dishes, choose cash or online payment, and complete your takeaway order directly with La Majestic.',
            'menu_cta_cart_label'        => 'view cart',
            'menu_cta_book_label'        => 'book a table',
            'menu_cta_image'             => 'assets/img/fine-dining.jpg',

            'gallery_page_intro'         => 'Explore the atmosphere, plates, cocktails, and elegant moments from La Majestic.',
            'gallery_banner_image'       => 'assets/img/fine-dining.jpg',
            'gallery_banner_subtitle'    => 'visual experience',
            'gallery_banner_title'       => 'Gallery',
            'gallery_subtitle'           => 'la majestic moments',
            'gallery_heading'            => 'Atmosphere, Plates & Detail',

            'booking_page_intro'         => 'Book your table for a refined dinner, private celebration, or relaxed fine-dining night at La Majestic.',
            'booking_banner_image'       => 'assets/img/ambience.jpg',
            'booking_banner_subtitle'    => 'reservation',
            'booking_banner_title'       => 'Book A Table',
            'booking_subtitle'           => 'reservation',
            'booking_heading'            => 'Reserve An Elegant Evening',
            'booking_request_text'       => 'Booking request',
            'booking_button_label'       => 'book a table',
            'booking_footer_note'        => 'Private dining, celebrations, and elegant evening reservations are welcome.',
            'booking_location_title'     => 'Windsor',
            'booking_address_label'      => 'Address',
            'booking_email_label'        => 'Email',
            'booking_hours_label'        => 'Dinner Time',
            'booking_closed_label'       => 'Closed',
            'booking_map_embed'          => 'https://www.google.com/maps?q=412%20High%20St%2C%20Windsor%20VIC%203181%2C%20Australia&output=embed',

            'cart_summary_text'          => 'Review your dishes, enter your details, and choose cash payment or secure online checkout for takeaway.',
            'cart_banner_image'          => 'assets/img/fine-dining.jpg',
            'cart_banner_subtitle'       => 'ecommerce dining',
            'cart_banner_title'          => 'Your Cart',
            'cart_title'                 => 'Your Selected Dishes',
            'cart_intro'                 => 'Review your cart, remove anything you do not need, and continue building your order from the La Majestic menu.',
            'cart_empty_title'           => 'Your cart is empty',
            'cart_empty_text'            => 'Start with our signature entrees, mains, and desserts to build your order.',
            'cart_summary_subtitle'      => 'order summary',
            'cart_summary_title'         => 'Takeaway Checkout',
            'cart_items_label'           => 'Items',
            'cart_subtotal_label'        => 'Subtotal',
            'cart_mode_heading'          => 'How would you like these dishes prepared?',
            'cart_mode_dinein_title'     => 'Book Table',
            'cart_mode_dinein_text'      => 'Serve these items at your reserved table',
            'cart_mode_takeaway_title'   => 'Takeaway',
            'cart_mode_takeaway_text'    => 'Pack these dishes for pickup or takeaway enquiry',
            'checkout_payment_heading'   => 'Choose your payment method',
            'checkout_cash_title'        => 'Cash Payment',
            'checkout_cash_text'         => 'Place the takeaway order now and pay at pickup or collection.',
            'checkout_online_title'      => 'Online Payment',
            'checkout_online_text'       => 'Pay securely online with card using Stripe Checkout.',
            'checkout_online_unavailable_text' => 'Online payment is currently unavailable. Please use cash payment.',
            'cart_help_title'            => 'Need help before you order?',
            'cart_form_name_label'       => 'Your Name',
            'cart_form_phone_label'      => 'Phone',
            'cart_form_email_label'      => 'Email',
            'cart_form_notes_label'      => 'Order Notes',
            'cart_form_notes_placeholder'=> 'Add pickup, table, or timing notes',
            'cart_recommended_subtitle'  => 'recommended dishes',
            'cart_recommended_heading'   => 'Add More To Your Table',
            'checkout_success_title'     => 'Order Confirmed',
            'checkout_success_text'      => 'Thank you. Your takeaway order has been received successfully.',
            'checkout_cancel_title'      => 'Payment Cancelled',
            'checkout_cancel_text'       => 'Your online payment was cancelled. You can return to checkout and try again.',
            'checkout_back_to_cart_label'=> 'Back to cart',
            'checkout_view_menu_label'   => 'Continue take away',

            'stripe_publishable_key'     => '',
            'stripe_secret_key'          => '',
            'stripe_currency'            => 'aud',

            'product_rating_label'       => 'Rating',
            'product_related_subtitle'   => 'you may also like',
            'product_related_heading'    => 'More From Our Menu',
        ];
    }
}
